site: DFTVIA
url: http://dftvia.tk/
title: Dftvia
description: Future Blog.
googlewebfonts: Fira+Code:wght@400;500;700
twitter:
  username: @dftvia
  card: summary
  creator: Thomas Lynch
author:
  twitter: @tetttris
  name: Thomas Lynch
  avatar:
  email: dftvia@gmail.com
  url: http://dftvia.tk/
permalink: pretty

baseurl: "http://dftvia.tk/"

highlighter: rouge

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
