site: Asko
url: https://tetttris.github.io/asko/
title: Asko
description: Simple and minimalistic jekyll blogging theme.
googlewebfonts: Fira+Code:wght@400;500;700
twitter:
  username: @tetttris
  card: summary
  creator: Thomas Lynch
author:
  twitter: @dftvia
  name: Thomas Lynch
  avatar:
  email: dftvia@gmail.com
  url: https://tetttris.github.io/asko/#
permalink: pretty

baseurl: ""

highlighter: rouge

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
